// Generated by dkgen from the atomictoolsx ABI. Do not edit.
#pragma once

#include <dwarfkit/contract.hpp>

namespace dwarfkit::gen::atomictoolsx {

inline const char* const abiBlob =
    "DmVvc2lvOjphYmkvMS4xAAkMYW5ub3VuY2VsaW5rAAQHY3JlYXRvcgRuYW1lA2tleQpwdWJsaWNfa2V5CWFzc2V0X2lkcwh1"
    "aW50NjRbXQRtZW1vBnN0cmluZwRhdXRoAAEFbm9uY2UGc3RyaW5nCmNhbmNlbGxpbmsAAQdsaW5rX2lkBnVpbnQ2NAljbGFp"
    "bWxpbmsAAwdsaW5rX2lkBnVpbnQ2NAdjbGFpbWVyBG5hbWURY2xhaW1lcl9zaWduYXR1cmUJc2lnbmF0dXJlCGNvbmZpZ19z"
    "AAMHdmVyc2lvbgZzdHJpbmcMbGlua19jb3VudGVyBnVpbnQ2NBRhdG9taWNhc3NldHNfYWNjb3VudARuYW1lBGluaXQAAAds"
    "aW5rc19zAAYHbGlua19pZAZ1aW50NjQHY3JlYXRvcgRuYW1lA2tleQpwdWJsaWNfa2V5CWFzc2V0X2lkcwh1aW50NjRbXRJh"
    "c3NldHNfdHJhbnNmZXJyZWQEYm9vbARtZW1vBnN0cmluZwxsb2dsaW5rc3RhcnQAAQdsaW5rX2lkBnVpbnQ2NApsb2duZXds"
    "aW5rAAUHbGlua19pZAZ1aW50NjQHY3JlYXRvcgRuYW1lA2tleQpwdWJsaWNfa2V5CWFzc2V0X2lkcwh1aW50NjRbXQRtZW1v"
    "BnN0cmluZwcAp4sKTU3nNAxhbm5vdW5jZWxpbmsAAAAAAADQsjYEYXV0aAAAAJwuRoWmQQpjYW5jZWxsaW5rAAAAgNNF6UxE"
    "CWNsYWltbGluawAAAAAAAJDddARpbml0AJCvyRhOFxmNDGxvZ2xpbmtzdGFydAAAAJwucjUZjQpsb2duZXdsaW5rAAIAAAAA"
    "MLcmRQNpNjQAAAhjb25maWdfcwAAAAAADKeLA2k2NAAAB2xpbmtzX3MAAAAAAA==";

inline const ABI& abi() {
    static const ABI decoded = [] {
        const auto parsed = Blob::from(abiBlob);
        if (parsed) {
            const auto value = Serializer::decode<ABI>(parsed->array);
            if (value) {
                return *value;
            }
        }
        return ABI();
    }();
    return decoded;
}

namespace Types {

struct announcelink {
    DK_STRUCT("announcelink")
    Name creator;
    PublicKey key;
    std::vector<uint64_t> asset_ids;
    std::string memo;
    DK_FIELDS(creator, key, asset_ids, memo)
};

struct auth {
    DK_STRUCT("auth")
    std::string nonce;
    DK_FIELDS(nonce)
};

struct cancellink {
    DK_STRUCT("cancellink")
    uint64_t link_id = 0;
    DK_FIELDS(link_id)
};

struct claimlink {
    DK_STRUCT("claimlink")
    uint64_t link_id = 0;
    Name claimer;
    Signature claimer_signature;
    DK_FIELDS(link_id, claimer, claimer_signature)
};

struct config_s {
    DK_STRUCT("config_s")
    std::string version;
    uint64_t link_counter = 0;
    Name atomicassets_account;
    DK_FIELDS(version, link_counter, atomicassets_account)
};

struct init {
    DK_STRUCT("init")
    DK_NO_FIELDS
};

struct links_s {
    DK_STRUCT("links_s")
    uint64_t link_id = 0;
    Name creator;
    PublicKey key;
    std::vector<uint64_t> asset_ids;
    bool assets_transferred = false;
    std::string memo;
    DK_FIELDS(link_id, creator, key, asset_ids, assets_transferred, memo)
};

struct loglinkstart {
    DK_STRUCT("loglinkstart")
    uint64_t link_id = 0;
    DK_FIELDS(link_id)
};

struct lognewlink {
    DK_STRUCT("lognewlink")
    uint64_t link_id = 0;
    Name creator;
    PublicKey key;
    std::vector<uint64_t> asset_ids;
    std::string memo;
    DK_FIELDS(link_id, creator, key, asset_ids, memo)
};

}  // namespace Types

class Contract : public dwarfkit::Contract {
public:
    explicit Contract(const std::shared_ptr<APIClient>& client,
                      const Name& account = Name::from("atomictoolsx"))
        : dwarfkit::Contract({.abi = atomictoolsx::abi(), .account = account, .client = client}) {}

    Result<Action> announcelink(const Types::announcelink& value, const ActionOptions& options = {}) const {
        DK_TRY(data, Serializer::encode(value));
        return action(Name::from("announcelink"), json(data.hexString()), options);
    }

    Result<Action> auth(const Types::auth& value, const ActionOptions& options = {}) const {
        DK_TRY(data, Serializer::encode(value));
        return action(Name::from("auth"), json(data.hexString()), options);
    }

    Result<Action> cancellink(const Types::cancellink& value, const ActionOptions& options = {}) const {
        DK_TRY(data, Serializer::encode(value));
        return action(Name::from("cancellink"), json(data.hexString()), options);
    }

    Result<Action> claimlink(const Types::claimlink& value, const ActionOptions& options = {}) const {
        DK_TRY(data, Serializer::encode(value));
        return action(Name::from("claimlink"), json(data.hexString()), options);
    }

    Result<Action> init(const Types::init& value, const ActionOptions& options = {}) const {
        DK_TRY(data, Serializer::encode(value));
        return action(Name::from("init"), json(data.hexString()), options);
    }

    Result<Action> loglinkstart(const Types::loglinkstart& value, const ActionOptions& options = {}) const {
        DK_TRY(data, Serializer::encode(value));
        return action(Name::from("loglinkstart"), json(data.hexString()), options);
    }

    Result<Action> lognewlink(const Types::lognewlink& value, const ActionOptions& options = {}) const {
        DK_TRY(data, Serializer::encode(value));
        return action(Name::from("lognewlink"), json(data.hexString()), options);
    }

    Result<dwarfkit::Table> configTable(const json& scope = {}) const {
        return table(Name::from("config"), scope);
    }

    Result<dwarfkit::Table> linksTable(const json& scope = {}) const {
        return table(Name::from("links"), scope);
    }
};

}  // namespace dwarfkit::gen::atomictoolsx
