// Byte-parity of the K1 nonce with Wharfkit/elliptic. The expected signature is
// generated by running crypto/sign.ts's exact algorithm (elliptic secp256k1
// with pers=[attempt] and the isCanonical retry) in node; see the session log.
// If this ever fails, the K1 nonce diverged from elliptic and every K1
// signature is non-parity.
#include <doctest/doctest.h>

#include <dwarfkit/antelope/chain/private_key.hpp>

using namespace dwarfkit;

TEST_SUITE("k1-parity") {
    TEST_CASE("elliptic signature bytes") {
        // key 5KQvfsPJ...co3zFu, message "I like turtles"
        const auto key = PrivateKey::from("5KQvfsPJ9YvGuVbLRLXVWPNubed6FWvV8yax6cNSJEzB4co3zFu").value();
        const std::vector<uint8_t> message = {'I', ' ', 'l', 'i', 'k', 'e', ' ',
                                              't', 'u', 'r', 't', 'l', 'e', 's'};
        const auto digest = Checksum256::hash(message);
        CHECK(digest.hexString() ==
              "e50da5010bca3f3ea824008ff6d885e7a877936c5834705e55c7fd0f1e0be47b");

        const auto signature = key.signMessage(message).value();
        // recid+31 (0x20) || r || s from elliptic
        CHECK(signature.data.hexString() ==
              "20"
              "206f84215393e2e94e119f157e6b539579c38dddbea03ae5a4ad0ce9c00e28eb"
              "1ee2964b0d83db21a3900693a3ea595749f53e64c58161707df7d664ec1e488d");

        // and the signature round-trips through the SIG_K1 string
        const auto reparsed = Signature::from(signature.toString()).value();
        CHECK(reparsed.equals(signature));
    }

    TEST_CASE("canonical retry path") {
        // message "turtles-1" needs 3 canonical attempts (pers = [1], [2], [3]),
        // exercising the outer retry loop's re-seeding of the DRBG
        const auto key = PrivateKey::from("5KQvfsPJ9YvGuVbLRLXVWPNubed6FWvV8yax6cNSJEzB4co3zFu").value();
        const std::vector<uint8_t> message = {'t', 'u', 'r', 't', 'l', 'e', 's', '-', '1'};
        const auto digest = Checksum256::hash(message);
        CHECK(digest.hexString() ==
              "247455b44d7464b67245320565f89e303a7cc4333c6b2a3e40798b72430c3c2e");
        const auto signature = key.signMessage(message).value();
        CHECK(signature.data.hexString() ==
              "20"
              "0d5ea92e37d28fc29c70d68a587e9cc29b9f714c445f0943b1a9f3829b6ccb0f"
              "28b0b4634d2f2332a9e2d64b9e21291e72b55d7db61ec9ae5d35f97161700fe6");
    }
}
